
sample: 
  - SRR1173967
  - SRR1173968

meta: 
  SRR1173967:
    replicate: 1
    strain: WT
    title: LB04_1
    treatment: LB
  SRR1173968:
    replicate: 2
    strain: WT
    title: LB04_2
    treatment: LB
build: "nc0009133" 
project: "ecoli_WT_SRA"
